apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-controller
spec:
  template:
    spec:
      containers:
        - image: {{namespace}}/serverless-k8s-controller:latest
          ports:
            - containerPort: 8082
