apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-scheduler
spec:
  template:
    spec:
      containers:
      - image: {{namespace}}/serverless-k8s-scheduler:latest
        ports:
          - containerPort: 8081
