apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-scheduler
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: raptorchoinl/serverless-k8s-scheduler:latest
        ports:
          - containerPort: 8081
