apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-server
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: raptorchoinl/serverless-k8s-api-server:latest
          ports:
            - containerPort: 8080