apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-server
spec:
  template:
    spec:
      containers:
        - image: {{namespace}}/serverless-k8s-api-server:latest
          ports:
            - containerPort: 8080